X   VAR  FLOAT
BJ  VAR  WORD
STOPLED		CON 9   ' Red LED
RUNLED		CON 10  ' Green LED

LOW RUNLED
LOW RUNLED
X = 0.0

MAINLOOP
   BUTTON 5,1,0,0,BJ,1,BANG
GOTO MAINLOOP

BANG:
   X = X + 1.0
   SEROUT S_OUT,I9600,["eCCE! ",REAL X,13]
   HIGH RUNLED
   PAUSE 21
   LOW RUNLED
   
GOTO MAINLOOP
  